#!/bin/bash
find -type f -name "*.gif" | rev | cut -d "/" -f 1 | cut -d . -f 2- | rev |
find -type f -name "*.gif" | rev | cut -d "/" -f 1 | cut -d . -f 2- | rev | LC_ALL=C
 find -type f -name "*.gif" | rev | cut -d "/" -f 1 | cut -d . -f 2- | rev | LC_ALL=C sort -f
